In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot("amazing restaurant",30)

[19, 18]

In [5]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[7, 9], [19, 18], [18, 20], [11, 25, 9], [2, 27, 25], [15, 9], [28, 27, 21], [9, 8], [9, 13], [29, 11]]


In [6]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 7  9  0  0]
 [19 18  0  0]
 [18 20  0  0]
 [11 25  9  0]
 [ 2 27 25  0]
 [15  9  0  0]
 [28 27 21  0]
 [ 9  8  0  0]
 [ 9 13  0  0]
 [29 11  0  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

c:\Workspace\MyProjects\DeepLearning\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
X = padded_reviews
y = sentiment

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
# verbose=2 will print the loss and accuracy for each epoch
# verbose=1 will print the loss and accuracy for each epoch in a single line
# verbose=0 will not print anything
model.fit(X, y, epochs=50, verbose=2)

Epoch 1/50
1/1 - 0s - 47ms/step - accuracy: 0.9000 - loss: 0.6392
Epoch 2/50
1/1 - 0s - 39ms/step - accuracy: 0.9000 - loss: 0.6378
Epoch 3/50
1/1 - 0s - 52ms/step - accuracy: 0.9000 - loss: 0.6364
Epoch 4/50
1/1 - 0s - 44ms/step - accuracy: 0.9000 - loss: 0.6350
Epoch 5/50
1/1 - 0s - 35ms/step - accuracy: 0.9000 - loss: 0.6336
Epoch 6/50
1/1 - 0s - 47ms/step - accuracy: 0.9000 - loss: 0.6322
Epoch 7/50
1/1 - 0s - 32ms/step - accuracy: 0.9000 - loss: 0.6308
Epoch 8/50
1/1 - 0s - 49ms/step - accuracy: 1.0000 - loss: 0.6293
Epoch 9/50
1/1 - 0s - 33ms/step - accuracy: 1.0000 - loss: 0.6279
Epoch 10/50
1/1 - 0s - 48ms/step - accuracy: 1.0000 - loss: 0.6264
Epoch 11/50
1/1 - 0s - 33ms/step - accuracy: 1.0000 - loss: 0.6250
Epoch 12/50
1/1 - 0s - 49ms/step - accuracy: 1.0000 - loss: 0.6235
Epoch 13/50
1/1 - 0s - 33ms/step - accuracy: 1.0000 - loss: 0.6220
Epoch 14/50
1/1 - 0s - 39ms/step - accuracy: 1.0000 - loss: 0.6205
Epoch 15/50
1/1 - 0s - 32ms/step - accuracy: 1.0000 - loss: 0.6190
Epoc

In [21]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5585


1.0

In [ ]:
# predict sentiment for a new review
new_review = "Nice food, great service"
new_encoded = one_hot(new_review, vocab_size)
new_padded = pad_sequences([new_encoded], maxlen=max_length, padding='post')
new_prediction = model.predict(new_padded)

# convert prediction to sentiment label
new_prediction = (new_prediction > 0.5).astype(int)
print(f"Predicted sentiment for '{new_review}': {new_prediction[0][0]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Predicted sentiment for 'Nice food, great service but horrible ambiance': 1


In [ ]:
# get the weights of the embedding layer - 
# weight matrix given the vocabulary size and embedding vector size
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights[13]

array([-0.06408861,  0.05637503,  0.02752245, -0.06079267,  0.0432574 ],
      dtype=float32)

In [14]:
weights[4]

array([ 0.04682212,  0.03650588, -0.02019431, -0.01179588,  0.01823748],
      dtype=float32)

In [33]:
weights[16]

array([ 0.0128377 ,  0.03549778,  0.05134471, -0.07147218,  0.03261041],
      dtype=float32)